name: Generate DBSummary HTML Report

on:
  workflow_dispatch: # Manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate HTML Report
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        sudo apt-get install -y sqlcmd
        sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME -i sql_scripts/DBSummary.sql -o reports/dbsummary.html -y 0

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: DBSummary-Report
        path: reports/dbsummary.html